### ISSUE TITLE
Support PostgreSQL as an Database 

### ISSUE THREAD

**Issue by Nino678190** [raphiz/nele#12]
I would be happy if you could add a integration for PostgreSQL

**Comment by raphiz** [comment]
Thank you for your suggestion. I am currently not actively working on this project, as I no longer have an active use case for it. However, you are welcome to submit a PR to introduce an abstraction for other DBs.

**Comment by Nino678190** [comment]
Hey, I find your Project cool, but I have written the code that I need in JS for my Application. When I find time, and my python skills are a bit better, i will try to create a PR with the code
