### ISSUE TITLE
Message-ID

### ISSUE THREAD

**Issue by fabianhauser** [raphiz/nele#3]
As defined in https://tools.ietf.org/html/rfc2822.html ; see also [email.utils.make_msgid](https://docs.python.org/2/library/email.util.html#module-email.utils)

This would allow grouping of email in various clients.

**Comment by raphiz** [comment]
Great idea! I'll have a look at it

**Comment by raphiz** [comment]
@fabianhauser checkout the branch feature/message-id (Commit db6955b)
I tested it - the `references` header is set properly on reply.

**Comment by fabianhauser** [comment]
I think this could be merged?

**Comment by raphiz** [comment]
merged :tada: Will make a release when #8 is merged as well
